# fly.toml app configuration file generated for fiatjafbuzz-bot on 2025-01-16T14:56:11Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fiatjafbuzz-bot'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[env]
  AUTHOR_NPUB = 'npub1y3yqdp44vg62ys8anqnjpx6cfprl848ev4lsmx5h4mznyz3xft9sen050h'
  DEBUG = false
  RELAYS= 'wss://relay.damus.io,wss://relay.snort.social,wss://nos.lol,wss://eden.nostr.land'

